export const people = [
  "Репина Ольга Витальевна",
  "Королькова Александра Сергеевна",
  "Савельева Екатерина Васильевна",
  "Курбанова Ханума Селимхановна",
  "Казенов Александр Владимирович",
  "Белякова Ирина Игоревна",
  "Каньшина Наталия Юрьевна",
  "Малородова Татьяна Николаевна",
  "Игнатьев Роман Владимирович",
  "Чуканова Светлана Алексеевна",
  "Андреечева Алена Андреевна",
  "Попова Юлия Ирековна",
  "Бетуганова Карина Назировна",
  "Черепахина Вера Сергеевна",
  "Дмитриева Наталья Алексеевна",
  "Кузнецова Мария Евгеньевна",
  "Титарева Наталья Валентиновна",
  "Бочкарева Лейла Махмадназаровна",
  "Быстрова Татьяна Викторовна",
  "Ткачева Светлана Васильевна",
  "Акинина Ольга Михайловна",
  "Кузнецова Наталья Викторовна",
  "Котова Людмила Викторовна",
  "Самошина Анжела Сиражудиновна",
  "Южанина Екатерина Николаевна",
  "Гармаш Маргарита Сергеевна",
  "Сальников Вячеслав Игоревич",
  "Губенко Ирина Михайловна",
  "Елесина Лада Владимировна",
  "Антонова Юлия Владимировна",
  "Михайлова Ирина Викторовна",
  "Карикова Тамара Владимировна",
  "Цховребов Василий Геннадиевич",
  "Черный Александр Геннадьевич",
  "Александрова Анастасия Александровна",
  "Петелин Сергей Васильевич",
  "Клеменок Диана Андреевна",
  "Хайбалиев Руслан Мадиевич",
  "Федосимова Ксения Сергеевна",
  "Лобачева Евгения Андреевна",
  "Анисимова Кристина Юрьевна",
  "Бизенков Олег Иванович",
  "Гафурова Марина Николаевна",
  "Ившин Александр Валентинович",
  "Мирошниченко Ольга Сергеевна",
  "Акиньшин Роман Александрович",
  "Логвин Владимир Владимирович",
  "Гундров Игорь Александрович",
  "Харланов Анатолий Викторович",
  "Скрипкина Маргарита Анатольевна",
  "Таджибаев Камолиддин Ганижанович",
  "Лукин Данила Николаевич",
  "Шамхалян Александр Феликсович",
  "Исматуллаев Мирзоулугбек Исматуллаевич",
  "Сайдалиев Алиер Валиевич",
  "Муковнин Дмитрий Викторович",
  "Аллаяров Улмас Ботирбоевич",
  "Грачев Николай Валерьевич",
  "Халбаев Зафар Зайнобудинович",
  "Лютикова Марина Викторовна",
  "Сидорова Кристина",
  "Ахмедова Шахноза Шахибаевна",
  "Кутузов Роман Владимирович",
  "Каратаев Павел Валерьевич",
  "Сарычева Екатерина Сергеевна",
  "Фомичев Даниил Андреевич",
  "Лайшева Виктория Юрьевна",
  "Типалов Николай Сергеевич",
  "Романов Эльшан Альшанович",
  "Бобровский Борис Александрович",
  "Султанов Рустам Амирасланович",
  "Кондратенко Иван Анатолиевич",
  "Мухутдинов Рамиль",
  "Сыркина Ольга Вячеславовна",
  "Епифанова Елена Валерьевна (Попова)",
  "Городнов Александр Владимирович",
  "Городнова Ирина",
  "Дворичанский Александр Владимирович",
  "Усков Денис Анатольевич",
  "Супель Александра Сергеевна",
  "Рассулов Михаил Владимирович",
  "Тищенко Владимир Геннадьевич",
  "Бокашова Татьяна Михайловна",
  "Трифонова Софья Владимировна",
  "Оспанова Анастасия Маратовна",
  "Чуприна Анастасия Геннадьевна",
  "Замалетдинова Елизавета Руслановна",
  "Ермакова София Ивановна",
  "Петрова Елена Ивановна",
  "Гордеева Александра Сергеевна",
  "Евсюнина Виктория Михайловна",
  "Конева Анна Андреевна",
  "Дубинина Евгения Евгеньевна",
  "Кашникова Галина Александровна",
  "Кипоть Екатерина Николаевна",
  "Зиновьева Елена Евгеньевна",
  "Фадеева Светлана Юрьевна",
  "Федченко Анна Владимировна",
  "Шульц Ирина Владимировна",
  "Френкина Анастасия Игоревна",
  "Кравченко Дмитрий Николаевич",
  "Кравченко Юлия Сергеевна",
  "Ишуков Тимур Камилевич",
  "Ишукова Эльвира Дамировна",
  "Тихомиров Юрий Вадимович",
  "Бобровский Даниил Александрович",
  "Канцерева Татьяна Николаевна",
  "Калинкина Елена Николаевна",
  "Константинова Екатерина Александровна",
  "Клепов Игорь Владимирович",
  "Моисеев Павел Сергеевич",
];

[
  {
    id: 1,
    title: "Репина Ольга Витальевна",
    email: "Repina.OV@mega-personal.ru",
  },
  {
    id: 2,
    title: "Королькова Александра Сергеевна",
    email: "Korolkova.AS@mega-personal.ru",
  },
  {
    id: 3,
    title: "Савельева Екатерина Васильевна",
    email: "Saveleva.EV@mega-personal.ru",
  },
  {
    id: 4,
    title: "Курбанова Ханума Селимхановна",
    email: "Kurbanova.HS@mega-personal.ru",
  },
  {
    id: 5,
    title: "Казенов Александр Владимирович",
    email: "Kazenov.AV@mega-personal.ru",
  },
  {
    id: 6,
    title: "Белякова Ирина Игоревна",
    email: "Belyakova.II@mega-personal.ru",
  },
  {
    id: 7,
    title: "Каньшина Наталия Юрьевна",
    email: "Kanshina.NY@mega-personal.ru",
  },

  {
    id: 8,
    title: "Малородова Татьяна Николаевна",
    email: "Malorodova.TN@mega-personal.ru",
  },
  {
    id: 9,
    title: "Игнатьев Роман Владимирович",
    email: "Ignatiev.RV@mega-personal.ru",
  },
  {
    id: 10,
    title: "Чуканова Светлана Алексеевна",
    email: "Chukanova.SA@mega-personal.ru",
  },
  {
    id: 11,
    title: "Андреечева Алена Андреевна",
    email: "Andreecheva.AA@mega-personal.ru",
  },
  {
    id: 12,
    title: "Попова Юлия Ирековна",
    email: "Popova.YI@mega-personal.ru",
  },
  {
    id: 13,
    title: "Бетуганова Карина Назировна",
    email: "Betuganova.KN@mega-personal.ru",
  },
  {
    id: 14,
    title: "Черепахина Вера Сергеевна",
    email: "cherepakhina.vs@mega-personal.ru",
  },
  {
    id: 15,
    title: "Дмитриева Наталья Алексеевна",
    email: "Dmitrieva.NA@mega-personal.ru",
  },
  {
    id: 16,
    title: "Кузнецова Мария Евгеньевна",
    email: "Kuznecova.ME@mega-personal.ru",
  },
  {
    id: 17,
    title: "Титарева Наталья Валентиновна",
    email: "Titareva.NV@mega-personal.ru",
  },
  {
    id: 18,
    title: "Бочкарева Лейла Махмадназаровна",
    email: "Bochkareva.LM@omega-personal.ru",
  },
  {
    id: 19,
    title: "Быстрова Татьяна Викторовна",
    email: "bystrova.tv@omega-personal.ru",
  },
  {
    id: 20,
    title: "Ткачева Светлана Васильевна",
    email: "Tkacheva.SV@mega-personal.ru",
  },
  {
    id: 21,
    title: "Акинина Ольга Михайловна",
    email: "Akinina.OM@omega-personal.ru",
  },
  {
    id: 22,
    title: "Кузнецова Наталья Викторовна",
    email: "Kuznecova.NV@mega-personal.ru",
  },
  {
    id: 23,
    title: "Котова Людмила Викторовна",
    email: "Kotova.LV@mega-personal.ru",
  },
  {
    id: 24,
    title: "Самошина Анжела Сиражудиновна",
    email: "Samoshina.AS@mega-personal.ru",
  },
  {
    id: 25,
    title: "Южанина Екатерина Николаевна",
    email: "Yuzhanina.EN@mega-personal.ru",
  },
  {
    id: 26,
    title: "Гармаш Маргарита Сергеевна",
    email: "Garmash.MS@mega-personal.ru",
  },
  {
    id: 27,
    title: "Сальников Вячеслав Игоревич",
    email: "-",
  },
  {
    id: 28,
    title: "Губенко Ирина Михайловна",
    email: "-",
  },
  {
    id: 29,
    title: "Елесина Лада Владимировна",
    email: "-",
  },
  {
    id: 30,
    title: "Антонова Юлия Владимировна",
    email: "Antonova.YV@mega-personal.ru",
  },
  {
    id: 31,
    title: "Михайлова Ирина Викторовна",
    email: "-",
  },
  {
    id: 32,
    title: "Карикова Тамара Владимировна",
    email: "-",
  },
  {
    id: 33,
    title: "Цховребов Василий Геннадиевич",
    email: "tskhovrebov.vg@mega-personal.ru",
  },
  {
    id: 34,
    title: "Черный Александр Геннадьевич",
    email: "cherniy.ag@mega-personal.ru",
  },
  {
    id: 35,
    title: "Александрова Анастасия Александровна",
    email: "Aleksandrova.AA@mega-personal.ru",
  },
  {
    id: 36,
    title: "Петелин Сергей Васильевич",
    email: "Petelin.SV@mega-personal.ru",
  },
  {
    id: 37,
    title: "Клеменок Диана Андреевна",
    email: "Klemenok.DA@mega-personal.ru",
  },
  {
    id: 38,
    title: "Хайбалиев Руслан Мадиевич",
    email: "Hajbaliev.RM@insgt.ru",
  },
  {
    id: 39,
    title: "Федосимова Ксения Сергеевна",
    email: "Fedosimova.KS@omega-personal.ru",
  },
  {
    id: 40,
    title: "Лобачева Евгения Андреевна",
    email: "Lobacheva.EA@mega-personal.ru",
  },
  {
    id: 41,
    title: "Анисимова Кристина Юрьевна",
    email: "Anisimova.KY@mega-personal.ru",
  },
  {
    id: 42,
    title: "Бизенков Олег Иванович",
    email: "Bizenkov.OI@mega-personal.ru",
  },
  {
    id: 43,
    title: "Гафурова Марина Николаевна",
    email: "Gafurova.MN@mega-personal.ru",
  },
  {
    id: 44,
    title: "Ившин Александр Валентинович",
    email: "Ivshin.AV@mega-personal.ru",
  },
  {
    id: 45,
    title: "Мирошниченко Ольга Сергеевна",
    email: "Miroshnichenko.OS@mega-personal.ru",
  },
  {
    id: 46,
    title: "Акиньшин Роман Александрович",
    email: "Akinshin.RA@mega-personal.ru",
  },
  {
    id: 47,
    title: "Логвин Владимир Владимирович",
    email: "Logvin.VV@mega-personal.ru",
  },
  {
    id: 48,
    title: "Гундров Игорь Александрович",
    email: "Gundrov.IA@mega-personal.ru",
  },
  {
    id: 49,
    title: "Харланов Анатолий Викторович",
    email: "Harlanov.AV@mega-personal.ru",
  },
  {
    id: 50,
    title: "Скрипкина Маргарита Анатольевна",
    email: "Skripkina.MA@mega-personal.ru",
  },
  {
    id: 51,
    title: "Таджибаев Камолиддин Ганижанович",
    email: "Tadzhibaev.KG@mega-personal.ru",
  },
  {
    id: 52,
    title: "Лукин Данила Николаевич",
    email: "Lukin.DN@mega-personal.ru",
  },
  {
    id: 53,
    title: "Шамхалян Александр Феликсович",
    email: "Shamhalyan.AF@mega-personal.ru",
  },
  {
    id: 54,
    title: "Исматуллаев Мирзоулугбек Исматуллаевич",
    email: "Ismatullaev.MI@mega-personal.ru",
  },
  {
    id: 55,
    title: "Сайдалиев Алиер Валиевич",
    email: "Sajdaliev.AV@mega-personal.ru",
  },
  {
    id: 56,
    title: "Муковнин Дмитрий Викторович",
    email: "Mukovnin.DV@mega-personal.ru",
  },
  {
    id: 57,
    title: "Аллаяров Улмас Ботирбоевич",
    email: "Allayarov.UB@mega-personal.ru",
  },
  {
    id: 58,
    title: "Грачев Николай Валерьевич",
    email: "Grachev.NV@mega-personal.ru ",
  },
  {
    id: 59,
    title: "Халбаев Зафар Зайнобудинович",
    email: "-",
  },
  {
    id: 60,
    title: "Лютикова Марина Викторовна",
    email: "Lyutikova.MV@mega-personal.ru",
  },
  {
    id: 61,
    title: "Сидорова Кристина",
    email: "-",
  },
  {
    id: 62,
    title: "Ахмедова Шахноза Шахибаевна",
    email: "Ahmedova.SSomega-personal.ru",
  },
  {
    id: 63,
    title: "Кутузов Роман Владимирович",
    email: "Kutuzov.RV@mega-personal.ru",
  },
  {
    id: 64,
    title: "Каратаев Павел Валерьевич",
    email: "Karataev.PV@mega-personal.ru",
  },
  {
    id: 65,
    title: "Сарычева Екатерина Сергеевна",
    email: "Sarycheva.ES@omega-personal.ru",
  },
  {
    id: 66,
    title: "Фомичев Даниил Андреевич",
    email: "Fomichev.DA@mega-personal.ru",
  },
  {
    id: 67,
    title: "Лайшева Виктория Юрьевна",
    email: "Laisheva.VY@mega-personal.ru",
  },
  {
    id: 68,
    title: "Типалов Николай Сергеевич",
    email: "Tipalov.NS@mega-personal.ru",
  },
  {
    id: 69,
    title: "Романов Эльшан Альшанович",
    email: "Romanov.EA@mega-personal.ru",
  },
  {
    id: 70,
    title: "Бобровский Борис Александрович",
    email: "Bobrovskij.BA@mega-personal.ru",
  },
  {
    id: 71,
    title: "Султанов Рустам Амирасланович",
    email: "Sultanov.RA@mega-personal.ru",
  },
  {
    id: 72,
    title: "Кондратенко Иван Анатолиевич",
    email: "Kondratenko.IA@mega-personal.ru",
  },
  {
    id: 73,
    title: "Мухутдинов Рамиль",
    email: "Muhutdinov.RE@mega-personal.ru",
  },
  {
    id: 74,
    title: "Сыркина Ольга Вячеславовна",
    email: "Syrkina.OV@mega-personal.ru",
  },
  {
    id: 75,
    title: "Епифанова Елена Валерьевна (Попова)",
    email: "Popova.EV@mega-personal.ru",
  },
  {
    id: 76,
    title: "Городнов Александр Владимирович",
    email: "Gorodnov.AV@mega-personal.ru",
  },
  {
    id: 77,
    title: "Городнова Ирина",
    email: "Gorodnova.IV@mega-personal.ru",
  },
  {
    id: 78,
    title: "Дворичанский Александр Владимирович",
    email: "Dvorichanskij.AV@mega-personal.ru",
  },
  {
    id: 79,
    title: "Усков Денис Анатольевич",
    email: "Uskov.DA@mega-personal.ru",
  },
  {
    id: 80,
    title: "Супель Александра Сергеевна",
    email: "-",
  },
  {
    id: 81,
    title: "Рассулов Михаил Владимирович",
    email: "Rassulov.MV@mega-personal.ru",
  },
  {
    id: 82,
    title: "Тищенко Владимир Геннадьевич",
    email: "Tishchenko.VG@mega-personal.ru",
  },
  {
    id: 83,
    title: "Бокашова Татьяна Михайловна",
    email: "Bokashova.TM@mega-personal.ru",
  },
  {
    id: 84,
    title: "Трифонова Софья Владимировна",
    email: "Trifonova.SV@mega-personal.ru",
  },
  {
    id: 85,
    title: "Оспанова Анастасия Маратовна",
    email: "Ospanova.AM@mega-personal.ru",
  },
  {
    id: 86,
    title: "Чуприна Анастасия Геннадьевна",
    email: "Chuprina.AG@mega-personal.ru",
  },
  {
    id: 87,
    title: "Замалетдинова Елизавета Руслановна",
    email: "Zamaletdinova.ER@mega-personal.ru",
  },
  {
    id: 88,
    title: "Ермакова София Ивановна",
    email: "Ermakova.SI@mega-personal.ru",
  },
  {
    id: 89,
    title: "Петрова Елена Ивановна",
    email: "Petrova.EI@mega-personal.ru",
  },
  {
    id: 90,
    title: "Гордеева Александра Сергеевна",
    email: "Gordeeva.AS@mega-personal.ru",
  },
  {
    id: 91,
    title: "Евсюнина Виктория Михайловна",
    email: "Evsyunina.VM@mega-personal.ru",
  },
  {
    id: 92,
    title: "Конева Анна Андреевна",
    email: "Koneva.AA@mega-personal.ru",
  },
  {
    id: 93,
    title: "Дубинина Евгения Евгеньевна",
    email: "Dubinina.EE@mega-personal.ru",
  },
  {
    id: 94,
    title: "Кашникова Галина Александровна",
    email: "Kashnikova.GA@mega-personal.ru",
  },
  {
    id: 95,
    title: "Кипоть Екатерина Николаевна",
    email: "Kipot.EN@mega-personal.ru",
  },
  {
    id: 96,
    title: "Зиновьева Елена Евгеньевна",
    email: "Zinovyeva.EE@mega-personal.ru",
  },
  {
    id: 97,
    title: "Фадеева Светлана Юрьевна",
    email: "Fadeeva.SY@mega-personal.ru",
  },
  {
    id: 98,
    title: "Федченко Анна Владимировна",
    email: "Fedchenko.AV@mega-personal.ru",
  },
  {
    id: 99,
    title: "Шульц Ирина Владимировна",
    email: "Shults.IV@mega-personal.ru",
  },
  {
    id: 100,
    title: "Френкина Анастасия Игоревна",
    email: "Frenkina.AI@omega-personal.ru",
  },
  {
    id: 101,
    title: "Кравченко Дмитрий Николаевич",
    email: "Kravchenko.DN@mega-personal.ru",
  },
  {
    id: 102,
    title: "Кравченко Юлия Сергеевна",
    email: "Kravchenko.YS@mega-personal.ru",
  },
  {
    id: 103,
    title: "Ишуков Тимур Камилевич",
    email: "Ishukov.TK@mega-personal.ru",
  },
  {
    id: 104,
    title: "Ишукова Эльвира Дамировна",
    email: "Ishukova.ED@mega-personal.ru",
  },
  {
    id: 105,
    title: "Тихомиров Юрий Вадимович",
    email: "Tihomirov.YV@mega-personal.ru",
  },
  {
    id: 106,
    title: "Бобровский Даниил Александрович",
    email: "Bobrovskij.DA@mega-personal.ru",
  },
  {
    id: 107,
    title: "Канцерева Татьяна Николаевна",
    email: "Kantsereva.TN@mega-personal.ru",
  },
  {
    id: 108,
    title: "Калинкина Елена Николаевна",
    email: "Kalinkina.EN@mega-personal.ru",
  },
  {
    id: 109,
    title: "Константинова Екатерина Александровна",
    email: "Ulyanova.EA@mega-personal.ru",
  },
  {
    id: 110,
    title: "Клепов Игорь Владимирович",
    email: "Klepov.IV@mega-personal.ru",
  },
  {
    id: 111,
    title: "Моисеев Павел Сергеевич",
    email: "Moiseev.PS@mega-personal.ru",
  },
];
